spring:
  datasource:
    url: ${db_url:jdbc:h2:mem:cuerp}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

# url - микросервис отпусков
# status_type - статус отпуска
vacations:
  host: ${VACATION_URL:176.113.82.235}
  port: ${VACATION_PORT:8082}
  url: "http://${vacations.host}:${vacations.port}/vacations/{profileListId}/{egarId}"
  status_type: "done"

clickup:
  api:
    tokens:
      - ${clickup_api_token}

fields:
  start_date:
    id: "58004edd-d04c-4edb-bed8-f6337397fd72"
  end_date:
    id: "879e67e3-eb65-45eb-9a82-94ac94470918"
  projects:
    id: "a34aa1f8-0ffc-4c1e-af06-f324b653610c"
